version: '3'

services:
  control-server:
    container_name: control-server
    restart: always
    image: "cmb87/skylink-nodeserver:latest"
    ports:
      - "5000:5000"

  control-joystick:
    container_name: control-joystick
    restart: always
    privileged: true
    image: "cmb87/skylink-thrustmaster:latest"
    ports:
     - "5001:5000"
    environment:
      #- LOGGING=CRITICAL
      - ENV_SOCKETIOSERVER=control-server
      #- ENV_CHANNELORDER=pitch roll throttle yaw aux1 aux2 aux3 aux4 # Multiwii
      - ENV_CHANNELORDER=throttle roll pitch yaw aux1 aux2 aux3 aux4 # Beta
    volumes:
      - /dev:/dev:ro

#volumes:
#  nginx:
#  prometheus:
#  dist:

