version: "3.5"

services:

  rosnoetic:
    image: ros:noetic-ros-base-focal
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: rosnoetic
    command: >
          sh -c "echo 'Installing dependencies...' &&
          apt update -y && apt install -y python3-pip iputils-ping &&
          apt install -y ros-noetic-rviz &&
          apt install -y ros-noetic-joint-state-publisher-gui &&
          apt install -y ros-noetic-robot-state-publisher &&
          apt install -y ros-noetic-gazebo-ros-pkgs &&
          apt install -y ros-noetic-gazebo-ros-control &&
          pip3 install xacro &&
          tail -f /dev/null"

    privileged: true
    network_mode: host
    volumes:
      - ./devws:/server_ws
      - ./launch.sh:/launch.sh
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/input:/dev/input # For Joystick
    environment:
      - DISPLAY=:1
    #  - DISPLAY=192.168.178.120:0.0
